slam_toolbox:
  ros__parameters:
    use_sim_time: false
    resolution: 0.05
    max_laser_range: 20.0
    minimum_time_interval: 0.5
    transform_publish_period: 0.05
    map_update_interval: 2.0
    publish_map: true
    map_file_name: "map"
    mode: "mapping"
    scan_topic: /scan
    base_frame: base_link
    odom_frame: odom
    map_frame: map
