image: office.pgm               # ไฟล์ภาพแผนที่ (อยู่ใน path เดียวกัน)
mode: trinary                   # ใช้โหมดแปลงภาพแบบสามค่าคือ 0, 100, -1 (free, occupied, unknown)
resolution: 0.05                # ความละเอียด: 1 พิกเซล = 0.05 เมตร
origin: [0.0, 0.0, 0.0]         # จุดอ้างอิงของแผนที่ (x, y, yaw)
negate: 0                       # ไม่กลับค่าสีของภาพ (0 = สีเข้มคือผนัง, 1 = สีเข้มคือพื้นที่โล่ง)
occupied_thresh: 0.65           # ถ้าความเข้ม >= 0.65 จะถือว่าเป็นผนัง
free_thresh: 0.25               # ถ้าความเข้ม <= 0.25 จะถือว่าเป็นทางเดิน
